from ex1.package import HFactory, TFactory

def test_creature_factories():
    factory1 = HFactory()
    base_creature1 = factory1.create_base()
    evolved_creature1 = factory1.create_evolved()
    print("Testing Creature with healing capability")
    print(" base:")
    print(base_creature1.describe())
    print(base_creature1.attack())
    print(base_creature1.heal())
    print(" evolved:")
    print(evolved_creature1.describe())
    print(evolved_creature1.attack())
    print(evolved_creature1.heal())
    print("\nTesting Creature with transforming capability")
    factory2 = TFactory()
    base_creature2 = factory2.create_base()
    evolved_creature2 = factory2.create_evolved()
    print(" base:")
    print(base_creature2.describe())
    print(base_creature2.attack())
    print(base_creature2.transform())
    print(base_creature2.attack())
    print(base_creature2.revert())
    print(" evolved:")
    print(evolved_creature2.describe())
    print(evolved_creature2.attack())
    print(evolved_creature2.transform())
    print(evolved_creature2.attack())
    print(evolved_creature2.revert())

if __name__ == "__main__":
    test_creature_factories()